branches:
  only:
    - master

dist: xenial
language: python
python:
  - '3.6'
  - '2.7'

install:
  - pip install -r test/test_requirements.txt
  - pip install .
  - pip install python-coveralls
  - pip install coverage

before_script:
  - git clone https://web.gin.g-node.org/heilerich/NeuroneTestdata
  - cd NeuroneTestdata
  - find . -not -path "./.git/*" \( -type f -o -type l \) -exec rm {} \; -exec wget
    -q --show-progress https://web.gin.g-node.org/heilerich/NeuroneTestdata/raw/master/{}
    -O {} \;
  - cd ..
  - mv NeuroneTestdata test/test_data
  - sudo fallocate -l 12G /swapfile
  - sudo chmod 600 /swapfile
  - sudo mkswap /swapfile
  - sudo swapon /swapfile
  - sudo swapon -s

script:
  - coverage run -m unittest discover -s test -t .

after_success:
  - coveralls

notifications:
  email: false
  pushover:
    on_failure: always
    on_success: change
    users:
      secure: GqZRvh4/iKVBffvJR80HEBoORfyHFNWvQZbrLj0e6nl04+ecajSYD4rqIcRJfHaXwL9ZReK0OUOVrLS2IP9GQxx/Os5NadYjSNGUQENvGX08fY4mLq9hYMe/ZzSf6Mo54Yeylx40//EslXOiB7wzrCFM9s/FkAuV3LoWfhy0hYhxhHWP+VzWUd5vzWD3N9y26nQEoLNHT6TkS1yC4uR/dxEuEaNRbvbj7i5Jn7WCat9fx6hMrEV4gDduJUdDhw94b320pu4p6sq0WEW6E/Nky6TU1remSzWGos5mboSoLQNNbiBF0HAoqg1feUETxpIiT8GrPbAfcf+da5K26Rb+ifPyqpQAgGDd1KT9hjVuJrDG9XWphk/53+cakrwKQYcrl89AfCSh1RvwrOySaYZlhOAliZkGAcZYOkaxO2v+GozOf0uoyHB4OSj/Eons/h9JCgHIBqsDu7f+wG9z/wLN0E3ACpDysZ693Zzmu1DZArMf/I/bKq7ZNmMaoDHweeC8ZuKYyggb8kaI0067MTAM6Dpf2PmUAKKwJkjcfuAUrQQw96BJt5Ig2ZH8cWE/A4h6Slxrx9L39IXa4tCmoEPxrFesPEjn+/FatzvJ6wyuTgj3UiWApPet+1YX8mAqTetSE0O7FDZD0A9VM3SaLeVd7C84ja1MmxXgx3w5i6nAWSY=
    api_key:
      secure: sk94rY5CCvzqq3OIN+Ui8DHiJe5YvTcO9y2JpZAjgHn+dmgMGu6QUqVd4tGGepAaR8bzTpME481IfWuOwA8ebvmx0YuL9TJYwZgA/z+MEqzq3Ymsz0YTP91bKsChXj9ufk+sfx2wCRQMEHh8mRvchzX9Dnbeja5HWsSFwty0NWIk2RdfOhszKW4xqLNSSVHHxmmLrMChXy0enaGNJynpFLCoZM4V55kK73gLlfc7VDmxbRLyGYOoGNFX35XF5ilnHJZZ2pq5S9kqCxZIPSz5r3vw5FvcgYlE2Ncy40l7jQPUeH11jyCUWgCHjxdfn+2wWwlnxWWzykUYkCLRqV3WCsPXfdGMYJLj/hRp/7vYDWWR1bGILkn8zhAvWoADga3aUwOmLzYnhfrxB3olExHT+54IwUPGuldad48GwziThevu3mO83l0rzHcCPaJzEuwKbLp77r0FkKlTXPZKgWxIUlxVhalGQq6qOrqT1JSmn9/mETFP1O+aWbQtcsIlAbcrJJGpNrkfgouIQIF0hcgCk8qPEnv9qRVj2VSHVm9/f7MbpsEUh9uurTghWLuIWoDJD+TANANh287rUxvusVZ49iILNJcrNv87mTLgoofEEptHdSgY3vw52UItPfyefU7RI+ikNNdQ/Jq0RP7LVHm9TP2zxa8tjD1gFL0MfpLip9E=
