language: python
python:
  - "3.6"

before_install:
  - sudo apt-get install -y git-annex
  - wget https://web.gin.g-node.org/G-Node/gin-cli-releases/raw/master/gin-cli-latest-linux-amd64.tar.gz
  - tar xvzf gin-cli-latest-linux-amd64.tar.gz
  - sudo mv gin /usr/bin
  - gin get heilerich/NeuroneTestdata
  - cd NeuroneTestdata
  - gin get-content .
  - cd ..
  - mv NeuroneTestdata test/test_data

install:
  - pip install -r test/test_requirements.txt
  - pip install .
  - pip install python-coveralls
  - pip install coverage

script:
  - coverage run -m unittest discover -s test -t .

after_success:
  - coveralls