name: Test

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}

jobs:
  download-data:
    name: Download Data
    runs-on: [self-hosted, linux]
    steps:
      - name: Get test data
        run: bash test/get_test_data.sh

  test:
    name: Test (Python ${{ matrix.python}})
    runs-on: [self-hosted, linux]
    needs: download-data

    strategy:
      fail-fast: false
      matrix:
        python: [2.7, 3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/test_requirements.txt
          pip install .
          pip install coverage python-coveralls
      - name: Run tests
        run: coverage run -m unittest discover -s test -t .
      - name: Coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: python-${{ matrix.python }}
